# Generated by Django 4.0.5 on 2022-06-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_user_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pagesCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ratelPeriod',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ratelPricePerDay',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('rental', 'rental'), ('sold', 'sold')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
