# Generated by Django 4.0.5 on 2022-06-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_remove_category_books_remove_user_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratelPricePerDay',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
